name: 'healthcare_dbt'
version: '1.0.0'
config-version: 2

profile: 'healthcare_dbt'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  healthcare_dbt:
    staging:
      +materialized: view
      +schema: STAGING
    intermediate:
      +materialized: view
      +schema: INTERMEDIATE
    marts:
      +materialized: table
      +schema: MART
      clinical:
        +materialized: table
      financial:
        +materialized: table
    reporting:
      +materialized: table
      +schema: REPORTING

seeds:
  healthcare_dbt:
    +schema: RAW

snapshots:
  healthcare_dbt:
    +schema: SNAPSHOTS
    +strategy: timestamp
    +unique_key: id
    +updated_at: updated_at