version: 2

models:
  # RAW CUSTOMERS
  - name: customers
    description: Raw customers data

    columns:
      - name: customer_id
        tests:
          - not_null
          - unique

      - name: email
        tests:
          - not_null

      - name: signup_date
        tests:
          - not_null

      - name: is_active
        tests:
          - accepted_values:
              values: ['Y', 'N']

  # RAW PRODUCTS